language: go

go:
  - 1.14

before_install:
  # We need Python to run pygmentize for generating HTML.
  - sudo apt-get update
  - sudo apt-get install python

install:
  - go get -u github.com/russross/blackfriday

script:
  - mkdir public
  - tools/build

env:
  - VERBOSE=1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: public
  fqdn: gobyexample.prahesa.id
  on:
    branch: master
